# Generated by Django 3.1.7 on 2021-05-30 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('telephone', models.CharField(max_length=11, verbose_name='Telephone')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Client Type',
                'verbose_name_plural': 'Client Types',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('classification', models.PositiveSmallIntegerField(verbose_name='Classification')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
                'ordering': ('-classification', 'name'),
            },
        ),
        migrations.CreateModel(
            name='HotelClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotel_chain.client', verbose_name='Client Reserve')),
                ('client_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotel_chain.clienttype', verbose_name='Client Type')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotel_chain.hotel', verbose_name='Hotel')),
            ],
            options={
                'verbose_name': 'Hotel Client',
                'verbose_name_plural': 'Hotel Clients',
                'unique_together': {('client', 'hotel', 'client_type')},
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], max_length=1, verbose_name='Status')),
                ('value', models.FloatField(verbose_name='Value')),
                ('rate_type', models.CharField(choices=[('WEN', 'Weekend Rate'), ('WEK', 'Week Rate')], max_length=3, verbose_name='Rate Type')),
                ('client_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotel_chain.clienttype', verbose_name='Client Type')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_chain.hotel', verbose_name='Hotel Rate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], max_length=1, verbose_name='Status')),
                ('hotel_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotel_chain.hotelclient', verbose_name='Hotel Client')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotel_chain.rate', verbose_name='Rate Reserve')),
            ],
            options={
                'verbose_name': 'Reserve',
                'verbose_name_plural': 'Reserves',
                'ordering': ('hotel_client', 'status'),
            },
        ),
        migrations.AddField(
            model_name='hotel',
            name='clients',
            field=models.ManyToManyField(through='hotel_chain.HotelClient', to='hotel_chain.Client', verbose_name='Hotel Clients'),
        ),
    ]
