# Generated by Django 3.1.7 on 2021-06-23 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_remove_reserve_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observations'),
        ),
    ]
